guardian/Prebid.js

modules.json

This makes it easier to track changes in adapters in use.
Build with command:
`gulp build --modules=modules.json`

Use modules.json to manage adapters in use.

---

modules/sonobiBidAdapter.js

This may be caused by transitioning to v1 bit by bit, but this should fix it.

Fix error in Prod

---

modifications.md
modules/consoleLoggingAnalyticsAdapter.js

To get an overview of auction events that can be tracked, and the information available with each event.
This is heavily based on https://github.com/guardian/Prebid.js/blob/master/modules/adkernelAdnAnalyticsAdapter.js

Create simple console-logging analytics adapter

---

modules/sonobiBidAdapter.js
test/spec/modules/sonobiBidAdapter_spec.js

Same as https://github.com/prebid/Prebid.js/pull/2970, except it's in our version.

Added render param in Sonobi adapter

---

test/spec/modules/ixBidAdapter_spec.js

Tests aren't running automatically as we have no CI for this project yet.  So this test did not reflect changes to TTL value made previously in #48.
(A lot of the tests in this project that we didn't write are quite ropy so if we ever decide to integrate CI we should be careful about which tests to include.)

Update ix bidder test

---

test/spec/unit/pbjs_api_spec.js

This is just a kind of sanity check.

Test for our bucket configuration

---

modules/guAnalyticsAdapter.js

Because added new fields and refactored so possible that something will break.

Bump analytics version

---

modifications.md

Add a small link in `modifications.md`

Add link to compare differences with upstream

---

modifications.md

so they can be clicked into from an IDE.

Make README links relative

---

GUARDIAN_modifications.md

Fix instruction with multiline commands, was showing as single line.

Tweak GUARDIAN_modifications.md

---

package-lock.json

Fixes critical vulnerability introduced in @babel/traverse 7.22.10
https://security.snyk.io/vuln/SNYK-JS-BABELTRAVERSE-5962462

Upgrade @babel/traverse to 7.23.2

---

package-lock.json
package.json

We also need to update @babel/core to make sure we fix the vulnerability introduced in @babel/traverse 7.22.10
https://security.snyk.io/vuln/SNYK-JS-BABELTRAVERSE-5962462

Update to @babel/core 7.23.2

---

package-lock.json
package.json

Updates crypto.js to 4.2.0 to resolve a vulnerability in the previous version.

Upgrade crypto.js to 4.2.0

---

.github/workflows/publish.yml
package.json

Add npm publish workflow

---

.github/workflows/publish.yml

Set npm auth token

---

package.json

Publish to @guardian/prebid.js

Publish to @guardian/prebid.js

---

.github/workflows/publish.yml
package.json

config for public scoped package

package.json config for private and repo url

---

package-lock.json
package.json

Bump the version of dset to 3.1.4 resolve a high severity vulnerability.

Bump dset version

---

package-lock.json
package.json

Updates express and body-parser to resolve a security vulnerability.

Update express and body-parser

---

package-lock.json
package.json

Build the build variants in parallel for a slight speed boost.

Build different versions in parallel
